config/routes.rb
Rails.application.routes.draw do
  get 'books/index'

  root 'books#index'
  resources :items
  get 'search', to: 'items#search'
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :media_type
end

app/models/media_type.rb
class MediaType < ApplicationRecord
  has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    goodreads = Goodreads.new(Goodreads.configuration)
    @read_books = goodreads.shelf(ENV['goodreads_id'], 'read', sort: 'date_read', per_page: 200)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @media_types = MediaType.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    goodreads = Goodreads.new(Goodreads.configuration)
    if params[:term] != ''
      if params[:media_type] == 'book'
        @response = goodreads.search_books(params[:term])
        @results = @response.results.work
      else
        flash[:alert] = "You must choose a media type."
        redirect_to root_path
      end
    else
      flash[:alert] = "You must enter a search term."
      redirect_to root_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :image_url, :media_type_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/books/index.html.erb
<h1>Books I've read</h1>
<div class="row flex-items-xs-center">
<% @read_books.books.each do |book| %>
  <%# book %>
    <%# book.book.title %>
    <%# book.book.authors.author.name %>
    <%# book.rating %>
  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
  <%= image_tag(book.book.image_url.gsub('m', 'l').gsub('col', 'com').gsub('ilages', 'images'), height: '300') %>
</div>
<% end %>
</div>
</div>

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="field">
    <%= f.label :media_type_id %>
    <%= f.text_field :media_type_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<%= form_tag(search_path, method: :get, role: 'search') do %>
  <%= text_field_tag :term, params[:term], autofocus: true %>
  <% @media_types.each do |media_type| %>
    <label>
      <%= radio_button_tag 'media_type', media_type.name %>
      <%= media_type.name.titleize %>
    </label>
  <% end %>
  <%= submit_tag 'Search', name: nil %>
<% end %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/search.html.erb
<% @results.each do |book| %>
  <h1><%= book.best_book.title %></h1>
  <h2><%= book.best_book.author.name %></h2>
  <br><br>
<% end %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @item.image_url %>
</p>

<p>
  <strong>Media type:</strong>
  <%= @item.media_type %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mediatrack</title>
    <%= csrf_meta_tags %>
    <script src="https://use.fontawesome.com/acc279b251.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div
  </body>
</html>